Revert "ARTEMIS-2319 Upgrading jboss-logging dependencies"
This reverts commit ad2ecd77d2cad093e7dca04af6d8b820947ef52a.

This was causing an issue when starting the server:

```
java.lang.NoClassDefFoundError: org/wildfly/common/net/HostName
	at org.jboss.logmanager.ExtLogRecord.<init>(ExtLogRecord.java:87)
	at org.jboss.logmanager.Logger.log(Logger.java:796)
	at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:44)
	at org.jboss.logging.Logger.logv(Logger.java:2226)
	at org.apache.activemq.artemis.integration.bootstrap.ActiveMQBootstrapLogger_$logger.serverStarting(ActiveMQBootstrapLogger_$logger.java:35)
	at org.apache.activemq.artemis.integration.FileBroker.start(FileBroker.java:68)
	at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:85)
```